### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by suprafun** [Shedelbower/MinecraftClone#1]
Hello, under what license is this project released under ? I would like to study it to learn from it. Thank you.

**Comment by Shedelbower** [comment]
Hello,

I've updated the project to include a [README](https://github.com/Shedelbower/MinecraftClone/blob/master/README.md) with license information.

In short, the code portion of the project is covered under the [MIT license](https://github.com/Shedelbower/MinecraftClone/blob/master/LICENSE.md). However, this does not include the artwork (image and audio files) which are based on official Minecraft assets. For these, you should consult Mojang's brand guidelines (https://account.mojang.com/documents/brand_guidelines).

So it's fine if you learn from this project, but if you want to release your own version I recommend replacing all the artwork.
